# This workflow will upload a NPM package when a release is created
name: Upload npm package

on:
  release:
    types: [published]
    
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'     
      - name: Install dependencies and build
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Install browsers
        run: npx playwright install
      - name: Run tests
        run: npm test
      - name: Publish npm package to npmjs.com
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
